import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <div className="min-h-screen bg-gradient-to-t from-[#EEFBF9] from-0% via-[#EBF2FC] via-100% px-4 md:px-32 pt-5 md:pt-10 md:pb-16 dark:from-[#091540] dark:via-[#04091B]">
          {children}
        </div>
      </body>
    </html>
  )
}
